const products = {
  1: "MICS",
  2: "COTTON",
  3: "WHEAT",
  4: "WOOD",
  5: "KOTTAL",
  6: "CHICKEN",
  7: "BANOLA",
  8: "BANOLA OIL",
  9: "TURRI",
  10: "IRON",
  11: "KHAL",
  12: "RICE",
  13: "CHARA",
  14: "SCRAP",
  15: "ROTI",
  16: "GATTA",
  17: "SURSON",
  18: "KHOKHARI",
  19: "MANGEN",
  20: "BOORA",
  21: "MARBAL",
  22: "CHARRIAN",
  23: "COTTON BALES",
  24: "BOTTEL",
  25: "MUD",
  26: "ALLO",
  27: "BAJRI",
  28: "GOVARA",
    29: "WATERMELON",
     30: "CHILKA",
     31: "KOLA",
     32: "ANIMAL",
};

export default products;